### ISSUE TITLE
ProgressDialog.show() 발생하는 오류

### ISSUE THREAD

**Issue by akswo119** [mousesd/AndroidAppBook#1]
안녕하세요. 정병관 입ㄴ다.

368p 예제 중
예제 처림 ProgressDialog를 show()하게 되면 
java.lang.reflect.invocationtargetexception 오류가 발생 하는데..

progressDialog = new ProgressDialog(getApplicationContext());
progressDialog.setProgressStyle(ProgressDialog.STYLE_SPINNER);
progressDialog.setMessage("로딩중..");

progressDialog.show();

이 부분을 외부 메서드로 만들어
progressDialog = new ProgressDialog(this);로 변경하면 
오류없이 실행됩니다.

context를 전달하는 하는방식에 따른 문제가 있는것 같은데
getApplicationContext()와 메인엑티비티에서 호출하는 this가 다른지...
확실한 이유를 잘모르겠습니다...

감사합니다.

**Comment by mousesd** [comment]
음. 먼저 발생하는 예외가 
android.view.WindowManager$BadTokenException: Unable to add window -- token null is not for an application
가 아닌가요?
언급된 상황을 보면 위 예외가 발생할거 같습니다.

아래부터는 위 예외가 발생한다는 가정하에 설명 합니다.
먼저 결론을 얘기하자면 `ProgressDialog(Context context)` 생성자에서 인수로 받는 context는
Activity Context가 필요 합니다.
근데 `getApplicationContext()` 메서드를 통해 Application Context가 전달되어 예외가 발생된 겁니다.

그럼.. Application Context와 Activity Context의 차이가 무엇인가? 라는 질문을 할거 같은데...
이건 좀더 시간이 지난 다음에 설명하는게 좋을거 같습니다.

당분간은 View, Dialog등 생성할때 인수로 전달되는 Context는 Activity Context이어야 한다 라고만 생각하면 좋을거 같습니다.

그리고 Anonymous 클래스에서 사용시에는 this 대신에 ActivityName.this를 사용해도 됩니다.
예들들어, ActivityName이 MainActivity이고 이 클래스의 Anonymous 클래스의 메서드에서 사용한다면
`progressDialog = new ProgressDialog(MainActivity.this);`
라고 사용하면 됩니다.

**Comment by proyoun83** [comment]
_Activity_.this 가 의미하는 것은 현재 활성화된 액티비티의 인스턴스이고,
_Activity_ 자체가 Context 클래스를 상속받아 만들어지므로 위 처럼 사용했을 때 컨텍스트 정보를 가져올 수 있습니다.
